# Generated by Django 4.2.3 on 2023-08-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('muscle', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=200)),
            ],
        ),
    ]
