# Generated by Django 4.2.3 on 2023-08-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_profile_user'),
        ('main_app', '0002_exercise'),
    ]

    operations = [
    ]
