# Generated by Django 4.2.3 on 2023-08-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_exercise_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('force', models.CharField(default='', max_length=100)),
                ('level', models.CharField(default='', max_length=100)),
                ('mechanic', models.CharField(default='', max_length=100)),
                ('equipment', models.CharField(default='', max_length=100)),
                ('primaryMuscles', models.CharField(default='', max_length=100)),
                ('secondaryMuscles', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('images', models.CharField(default='', max_length=100)),
                ('instructions', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
