# Generated by Django 4.2.3 on 2023-08-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_importedexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseInWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('tempo', models.CharField(blank=True, max_length=10, null=True)),
                ('rest', models.CharField(blank=True, max_length=10, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.importedexercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(through='main_app.ExerciseInWorkout', to='main_app.importedexercise')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseinworkout',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.workout'),
        ),
    ]
