# Generated by Django 4.2.3 on 2023-08-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_exercise_difficulty_remove_exercise_muscle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='force',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='images',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primaryMuscles',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondaryMuscles',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
