# Generated by Django 4.2.3 on 2023-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_exercise_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='importedexercise',
            name='instructions',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
