# Generated by Django 4.2.3 on 2023-08-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_exercise_category_alter_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('ft', 'Feet')], default='cm', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', max_length=3),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='force',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='images',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primaryMuscles',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondaryMuscles',
            field=models.CharField(default='', max_length=100),
        ),
    ]
