# Generated by Django 4.2.3 on 2023-08-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_exercise_category_alter_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('ft', 'Feet')], default='cm', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', max_length=3),
        ),
    ]
