# Generated by Django 4.2.3 on 2023-08-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile_height_unit_profile_weight_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height_unit',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_unit',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
