# Generated by Django 4.2.3 on 2023-08-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_exerciseinworkout_workout_exerciseinworkout_workout'),
        ('main_app', '0006_alter_exercise_instructions_and_more'),
    ]

    operations = [
    ]
