# Generated by Django 4.2.3 on 2023-08-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_profile_height_unit_alter_profile_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('cm', 'Centimeters'), ('ft', 'Feet')], default='cm', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', max_length=3),
        ),
    ]
