# Generated by Django 4.2.3 on 2023-08-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
    ]
