# Generated by Django 4.2.3 on 2023-08-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_workout_date_workout_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='force',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('e', 'Expert')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondaryMuscles',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
