# Generated by Django 4.2.3 on 2023-08-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_exercise_category_alter_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('e', 'Expert')], default='b', max_length=20),
        ),
        migrations.AlterField(
            model_name='importedexercise',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importedexercise',
            name='equipment',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importedexercise',
            name='force',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importedexercise',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('e', 'Expert')], default='b', max_length=20),
        ),
        migrations.AlterField(
            model_name='importedexercise',
            name='mechanic',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importedexercise',
            name='secondaryMuscles',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
