# Generated by Django 4.2.3 on 2023-08-07 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_alter_exercise_level_alter_importedexercise_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedexercise',
            name='imported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='importedexercise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
