# Generated by Django 4.2.3 on 2023-08-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_importedexercise_imported_importedexercise_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedexercise',
            name='images',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
