# Generated by Django 4.2.3 on 2023-08-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedexercise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imported_exercise_photos/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
